### ISSUE TITLE
Missing build instructions for exe

### ISSUE THREAD

**Issue by puenktchen** [fancybits/chrome-capture-for-channels#4]
@tmm1 Can you please add build instructions for creating an executable to the Readme file? I can run your great app just fine in a development environment. Also was even able to create an exe file with the pkg command. But when starting the exe, the window is closed immediately. So i must be doing something wrong. Thanks!

**Comment by tmm1** [comment]
If it doesn't work the problem is with pkg

https://github.com/fancybits/chrome-capture-for-channels/blob/432bfb0146962dc9207a97901cab16b300869163/package.json#L32
